# Generated by Django 5.1.15 on 2026-07-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_user_delete_cascade"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventticket",
            name="scanned_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Set when the ticket QR/barcode is scanned at the venue on event day. Only scanned tickets count as attendance for gathering eligibility.",
                null=True,
            ),
        ),
    ]
