# Generated by Django 5.1.15 on 2026-07-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_diditwebhookdelivery"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="identityverificationsession",
            new_name="accounts_id_user_id_e5a2cb_idx",
            old_name="accounts_id_user_id_6d2f0a_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="accounts_us_verific_987f5f_idx",
            old_name="accounts_us_verific_0f0a2a_idx",
        ),
        migrations.AlterField(
            model_name="user",
            name="nationality_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ISO 3166-1 alpha-2 nationality; set from ID verification OCR.",
                max_length=2,
            ),
        ),
    ]
