# Generated by Django 5.1.15 on 2026-07-17 13:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_profile_and_follows'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityFounder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=32)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='userfollow',
            new_name='accounts_us_followe_30bd2d_idx',
            old_name='accounts_us_followe_0f0f62_idx',
        ),
        migrations.RenameIndex(
            model_name='userfollow',
            new_name='accounts_us_followi_a56db0_idx',
            old_name='accounts_us_followi_4a3f1d_idx',
        ),
        migrations.AddField(
            model_name='cityfounder',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='city_founder_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cityfounder',
            index=models.Index(fields=['city_id', 'status'], name='accounts_ci_city_id_9eee7a_idx'),
        ),
        migrations.AddIndex(
            model_name='cityfounder',
            index=models.Index(fields=['status', 'created_at'], name='accounts_ci_status_6de00e_idx'),
        ),
        migrations.AddConstraint(
            model_name='cityfounder',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('city_id',), name='uniq_active_city_founder_per_city'),
        ),
    ]
