# Generated by Django 5.1.15 on 2026-07-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_clear_non_superuser_django_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='When True, City Founder must set a new password before using the dashboard.'),
        ),
    ]
