# Generated by Django 5.1.15 on 2026-07-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_user_profile_onboarding"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bypass_gathering_attendance",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="When True, admin bypasses the event-attendance gate for creating/joining gatherings (demo / support only).",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gathering_attendance_credit",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Admin-granted attendance credits toward gathering create/join eligibility. Added on top of real scanned event tickets.",
            ),
        ),
    ]
