# Generated by Django 5.1.15 on 2026-07-27 09:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gathering",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("community_id", models.UUIDField(db_index=True)),
                ("city_id", models.UUIDField(db_index=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("area", models.CharField(max_length=255)),
                (
                    "exact_location",
                    models.CharField(
                        blank=True,
                        help_text="Exact address / map pin — only revealed to joined attendees.",
                        max_length=255,
                    ),
                ),
                ("map_link", models.URLField(blank=True, max_length=500)),
                (
                    "cover_image_key",
                    models.CharField(
                        blank=True,
                        help_text="S3 object key for the gathering cover image.",
                        max_length=512,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "max_attendees",
                    models.PositiveIntegerField(
                        default=20,
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                ("is_cancelled", models.BooleanField(default=False)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_gatherings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at", "title"],
            },
        ),
        migrations.CreateModel(
            name="GatheringAttendee",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("community_id", models.UUIDField(db_index=True)),
                ("city_id", models.UUIDField(db_index=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "gathering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendees",
                        to="gatherings.gathering",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gathering_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="gathering",
            index=models.Index(fields=["starts_at"], name="gatherings__starts__ca46b5_idx"),
        ),
        migrations.AddIndex(
            model_name="gathering",
            index=models.Index(
                fields=["community_id", "starts_at"], name="gatherings__communi_98feca_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="gathering",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_attendees__gte", 2), ("max_attendees__lte", 20)),
                name="gathering_max_attendees_within_hard_cap",
            ),
        ),
        migrations.AddIndex(
            model_name="gatheringattendee",
            index=models.Index(
                fields=["gathering", "is_active"], name="gatherings__gatheri_b28187_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="gatheringattendee",
            constraint=models.UniqueConstraint(
                fields=("gathering", "user"), name="uniq_gathering_attendee_per_user"
            ),
        ),
    ]
