# Generated by Django 5.1.15 on 2026-07-27 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0002_user_delete_cascade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gathering',
            options={'ordering': ['-created_at', 'title']},
        ),
        migrations.AddIndex(
            model_name='gathering',
            index=models.Index(fields=['-created_at'], name='gatherings__created_fc45dc_idx'),
        ),
    ]
