# Generated by Django 5.1.15 on 2026-07-29 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remove_creators_from_attendees(apps, schema_editor):
    """Hosts do not occupy an attendee seat — strip legacy auto-joins."""
    GatheringAttendee = apps.get_model("gatherings", "GatheringAttendee")
    GatheringAttendee.objects.filter(user_id=models.F("gathering__creator_id")).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0003_gathering_order_newest_first'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gathering',
            name='deletion_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gathering',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gathering',
            name='deletion_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gathering',
            name='deletion_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_gathering_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gathering',
            name='deletion_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending admin approval'), ('rejected', 'Rejected')], db_index=True, default='none', max_length=16),
        ),
        migrations.AddIndex(
            model_name='gathering',
            index=models.Index(fields=['deletion_status', 'community_id'], name='gatherings__deletio_130ee1_idx'),
        ),
        migrations.RunPython(remove_creators_from_attendees, migrations.RunPython.noop),
    ]
