# Generated by Django 5.1.15 on 2026-07-06 11:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('country_code', models.CharField(db_index=True, max_length=2)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CityAnnouncement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityAnnouncement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('community_id', models.UUIDField(db_index=True)),
                ('city_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=160)),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('logo_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communities', to='tenancy.city')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['city', 'is_active'], name='tenancy_com_city_id_4e45f1_idx')],
                'constraints': [models.UniqueConstraint(fields=('city', 'slug'), name='uniq_community_slug_per_city')],
            },
        ),
    ]
