# Generated by Django 5.1.15 on 2026-07-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0004_remove_allows_residence_cleanup"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="city",
            new_name="tenancy_cit_country_4d3f65_idx",
            old_name="tenancy_cit_country_6e0f0a_idx",
        ),
        migrations.RenameIndex(
            model_name="community",
            new_name="tenancy_com_city_id_78fdb9_idx",
            old_name="tenancy_com_city_id_8b2c4d_idx",
        ),
    ]
