# Generated by hand - initial migration for trust_voting
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency('accounts.User'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingWindow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('community_id', models.UUIDField(db_index=True)),
                ('city_id', models.UUIDField(db_index=True)),
                ('event_id', models.UUIDField(db_index=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('prompt_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrustVote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('community_id', models.UUIDField(db_index=True)),
                ('city_id', models.UUIDField(db_index=True)),
                ('vote', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrustScore',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('score', models.FloatField(default=0.0)),
                ('last_computed_at', models.DateTimeField(null=True, blank=True)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=models.CASCADE, related_name='trust_score', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='AdminTrustFlag',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('score', models.FloatField(null=True, blank=True)),
                ('previous_score', models.FloatField()),
                ('new_score', models.FloatField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=models.CASCADE, related_name='trust_flags', to='accounts.user')),
            ],
        ),
    ]
