# Generated by Django 5.1.15 on 2026-07-17 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founders', '0003_rename_cityfounder_to_founder_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='founder',
            name='uniq_active_founder_per_city',
        ),
        migrations.AlterField(
            model_name='founder',
            name='status',
            field=models.CharField(choices=[('pending_first_login', 'Pending first login'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], db_index=True, default='pending_first_login', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='founder',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending_first_login', 'active'])), fields=('city_id',), name='uniq_assigned_founder_per_city'),
        ),
    ]
