# Generated by Django 5.1.15 on 2026-07-17 16:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("founders", "0004_pending_first_login_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="FounderApplicationSyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_error", models.TextField(blank=True)),
                ("last_sync_row_count", models.PositiveIntegerField(default=0)),
                ("spreadsheet_id", models.CharField(blank=True, max_length=128)),
                ("spreadsheet_url", models.URLField(blank=True, max_length=512)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Founder application sync state",
                "verbose_name_plural": "Founder application sync state",
            },
        ),
        migrations.CreateModel(
            name="FounderApplication",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "sheet_row",
                    models.PositiveIntegerField(
                        help_text="1-based row number in the Google Sheet (row 1 is headers).",
                        unique=True,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254)),
                ("country_name", models.CharField(blank=True, db_index=True, max_length=255)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                (
                    "answers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full form row keyed by original sheet headers.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_reviewed", "Not reviewed"),
                            ("reviewed", "Reviewed"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="not_reviewed",
                        max_length=32,
                    ),
                ),
                ("spreadsheet_id", models.CharField(blank=True, max_length=128)),
                ("sheet_gid", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "ordering": ["-submitted_at", "-sheet_row"],
                "indexes": [
                    models.Index(
                        fields=["status", "submitted_at"], name="founders_fo_status_036b16_idx"
                    ),
                    models.Index(
                        fields=["country_name", "submitted_at"],
                        name="founders_fo_country_e40ea3_idx",
                    ),
                ],
            },
        ),
    ]
