# Generated by Django 5.1.15 on 2026-07-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('admin.login', 'Admin login'), ('city_founder.create', 'Create city founder'), ('city_founder.update', 'Update city founder'), ('city_founder.delete', 'Delete city founder')], db_index=True, max_length=64),
        ),
    ]
