# Generated by Django 5.1.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0002_city_founder_and_audit_actions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("admin.login", "Admin login"),
                    ("city_founder.create", "Create city founder"),
                    ("city_founder.update", "Update city founder"),
                    ("city_founder.delete", "Delete city founder"),
                    ("user.delete", "Delete user"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
    ]
