# Generated by Django 5.1.15 on 2026-07-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_user_delete_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('admin.login', 'Admin login'), ('city_founder.create', 'Create city founder'), ('city_founder.update', 'Update city founder'), ('city_founder.delete', 'Delete city founder'), ('admin.create', 'Create admin'), ('admin.update', 'Update admin'), ('admin.delete', 'Delete admin'), ('user.delete', 'Delete user'), ('user.role_update', 'Update user role'), ('admin.password_change', 'Change password'), ('admin.profile_update', 'Update profile'), ('gathering.deletion_approve', 'Approve gathering deletion'), ('gathering.deletion_reject', 'Reject gathering deletion')], db_index=True, max_length=64),
        ),
    ]
