# Generated by Django 5.1.15 on 2026-07-28 08:35

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("city_id", models.UUIDField(db_index=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[("city_wide", "City-wide"), ("community", "Community")],
                        db_index=True,
                        default="city_wide",
                        max_length=32,
                    ),
                ),
                (
                    "community_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Required when scope=community; must be null for city_wide.",
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("restaurant", "Restaurant"),
                            ("grocery", "Grocery"),
                            ("transport", "Transport"),
                            ("fitness", "Fitness"),
                            ("entertainment", "Entertainment"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="restaurant",
                        max_length=64,
                    ),
                ),
                ("area", models.CharField(blank=True, max_length=120)),
                ("short_description", models.CharField(blank=True, max_length=280)),
                ("description", models.TextField(blank=True)),
                (
                    "discount_percent",
                    models.PositiveSmallIntegerField(
                        default=15,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                ("hours_label", models.CharField(blank=True, max_length=64)),
                ("hours_range", models.CharField(blank=True, max_length=64)),
                ("website", models.CharField(blank=True, max_length=200)),
                ("website_url", models.URLField(blank=True, max_length=500)),
                ("maps_url", models.URLField(blank=True, max_length=500)),
                (
                    "image_key",
                    models.CharField(
                        blank=True,
                        help_text="S3 object key for the list-card image.",
                        max_length=512,
                    ),
                ),
                (
                    "cover_image_key",
                    models.CharField(
                        blank=True,
                        help_text="S3 object key for the detail hero image.",
                        max_length=512,
                    ),
                ),
                (
                    "map_image_key",
                    models.CharField(
                        blank=True,
                        help_text="S3 object key for the location map preview.",
                        max_length=512,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["city_id", "is_active", "sort_order"],
                        name="guidebook_p_city_id_5eacce_idx",
                    ),
                    models.Index(
                        fields=["city_id", "category"], name="guidebook_p_city_id_f6efa5_idx"
                    ),
                    models.Index(
                        fields=["community_id", "is_active"], name="guidebook_p_communi_a3153b_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("community_id__isnull", True), ("scope", "city_wide")),
                            models.Q(("community_id__isnull", False), ("scope", "community")),
                            _connector="OR",
                        ),
                        name="partner_scope_matches_community_id",
                    )
                ],
            },
        ),
    ]
